inbox:
  - destination: true
    config:
      kind: org
      path: "~/documents/org/gtd/inbox.org"
  - destination: false
    config:
      kind: tasks
      title: Inbox
      client_secret: !keyring gtd/google-client-secret
      client_id: !keyring gtd/google-client-id
      refresh_token: !keyring gtd/google-refresh-token
  - destination: false
    config:
      kind: tickler
      path: "~/documents/org/gtd/tickler.org"
  - destination: false
    config:
      kind: spotify
      playlist_id: "4bFiyVW2XORyV5w9hPE6bm"
      client_secret: !keyring gtd/spotify-client-secret
      client_id: !keyring gtd/spotify-client-id
      refresh_token: !keyring gtd/spotify-refresh-token
  - destination: false
    config:
      kind: remarkable
      path: "/Inbox"
      hash_cache_path: "~/.config/gtd/remarkable-hash"
      anthropic_api_key: !keyring gtd/anthropic-api-key
