;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+STARTUP: overview

* Generic
** Personal Info
#+begin_src emacs-lisp :tangle yes
(setq user-full-name "Bart Frenk"
      user-mail-address "bart.frenk@gmail.com")
#+end_src

** Core
The command =save-buffer= is bound to =C-x C-s=, while =save-some-buffers= is
bound to =C-x s=. These keybindings are easy to mix up while typing; that is
annoying since the latter command steals focus to the minibuffer while waiting
for a response.

#+begin_src emacs-lisp :tangle yes
(global-unset-key (kbd "C-x s"))
#+end_src

** Appearance
#+begin_src emacs-lisp :tangle yes
(setq doom-theme 'doom-vibrant)
(setq doom-modeline-height 25)
#+end_src

#+begin_src emacs-lisp :tangle yes
(after! doom
  (setq doom-font (font-spec :family "Hack Nerd Font" :size 11)
        display-line-numbers-type t)
  (setq-default line-spacing 4)
  (setq doom-font-increment 1))
#+end_src

#+RESULTS:
: 1

** Eglot
Inlay hints do not work as well always; there is info on this [[https://www.reddit.com/r/emacs/comments/1n7y3jp/eglot_inlay_hints_only_show_after_editing_the/][here]].

#+begin_src emacs-lisp :tangle yes
(add-hook 'eglot-managed-mode-hook (lambda () (eglot-inlay-hints-mode -1)))
#+end_src
** Flymake

Do not print diagnostic information in the minibuffer.
#+begin_src emacs-lisp :tangle yes
(after! flymake
  (add-to-list 'flymake-diagnostic-format-alist '(:eldoc-echo nil)))
#+end_src

Print full diagnostic information in the popon frame, instead of only the first
line.
#+begin_src emacs-lisp :tangle yes
(after! flymake
  (defun custom-flymake-popon-format-diagnostic (diagnostic)
    "Format DIAGNOSTIC to text."
    (with-temp-buffer
      (insert
       "* "
       (propertize
        (string-join (split-string (flymake-diagnostic-text diagnostic '(message)) "[\n\r]") ": ")
        'face (flymake--lookup-type-property
               (flymake-diagnostic-type diagnostic) 'mode-line-face)))

      ;; Break long lines.
      (goto-char (point-min))
      (let ((last-whitespace nil)
            (last-char-whitespace-p nil))
        (while (not (eobp))
          (if (not (member (buffer-substring-no-properties
                            (point) (1+ (point)))
                           '(" " "\t")))
              (setq last-char-whitespace-p nil)
            (unless last-char-whitespace-p
              (setq last-whitespace (point))
              (setq last-char-whitespace-p t)))
          (when (>= (current-column) flymake-popon-width)
            (save-excursion
              (when last-whitespace
                (goto-char last-whitespace))
              (insert "\n  ")
              (while (member (buffer-substring-no-properties
                              (point) (1+ (point)))
                             '(" " "\t"))
                (delete-char 1))))
          (right-char)))
      (buffer-string))))

(setq flymake-popon-diagnostic-formatter #'custom-flymake-popon-format-diagnostic)


#+end_src

#+RESULTS:
: custom-flymake-popon-format-diagnostic

* Global keybindings

#+begin_src emacs-lisp :tangle yes
(defun consult-flymake-project ()
  (interactive)
  (consult-flymake 1))

(defun toggle-inlay-hints-mode ()
  (interactive)
  (eglot-inlay-hints-mode 'toggle)
  (message "%s" eglot-inlay-hints-mode))

(map! :leader
      :desc "Jump to next diagnoses"
      "c n" #'flymake-goto-next-error)
(map! :leader
      :desc "Jump to previous diagnoses"
      "c p" #'flymake-goto-prev-error)
(map! :leader
      :desc "Show project diagnostics"
      "c X" #'consult-flymake-project)
#+end_src

#+begin_src emacs-lisp :tangle yes
(defun toggle-treemacs ()
  "Toggle focus between Treemacs and current buffer."
  (interactive)
  (if (treemacs-is-treemacs-window-selected?)
      (other-window 1)
    (treemacs-select-window)))

(map! :leader
      :desc "Switch between treemacs and open buffer"
      "-" #'toggle-treemacs)
#+end_src

* Languages
** Chordpro
#+begin_src emacs-lisp :tangle yes
(add-hook 'chordpro-mode
          (lambda ()
            (visual-fill-column-mode 1)))
#+end_src

** Org
#+begin_src emacs-lisp :tangle yes
(setq org-directory "~/documents/org/"
      org-noter-notes-search-path "~/documents/notes/"
      org-roam-directory "~/documents/roam")
#+end_src

** Python
#+begin_src emacs-lisp :tangle yes
(after! python
  (set-eglot-client! '(python-mode python-ts-mode)
                     '("basedpyright-langserver" "--stdio")
                     '("ruff" "server")))

(defun activate-venv ()
  (interactive)
  (if-let ((root-dir (projectile-project-root)))
      (let ((venv-dir (concat (file-name-as-directory root-dir) ".venv")))
        (pyvenv-activate venv-dir)
        (message "Activated virtualenv at %s" venv-dir))
    (message "Could not find virtualenv")))

(after! python
  (use-package! python-black
    :demand t
    :after python)
(add-hook! 'python-mode-hook #'python-black-on-save-mode))
#+end_src

Do not display Python generated files in treemacs
#+begin_src emacs-lisp :tangle yes
(after! treemacs
  (defun treemacs-ignore-pycache (file _)
    (string= file "__pycache__"))
  (push #'treemacs-ignore-pycache treemacs-ignored-file-predicates))
#+end_src

- [ ] Automatically restart eglot when switching virtualenv
- [ ] Automatically reset virtualenv (and restart eglot) when switching project

** Lisp
#+begin_src emacs-lisp :tangle yes
(use-package! paredit
  :defer t
  :commands paredit-mode
  :hook
  (emacs-lisp-mode . paredit-mode))

(use-package! enhanced-evil-paredit
  :defer t
  :commands enhanced-evil-paredit-mode
  :hook
  (paredit-mode . enhanced-evil-paredit-mode))
#+end_src

- [ ] Use paredit instead of parinfer

** Shell Scripts
#+begin_src emacs-lisp :tangle yes
(add-to-list 'auto-mode-alist '("\\.zsh-theme\\'" . bash-ts-mode))
#+end_src

** Rust
See https://lists.gnu.org/archive/html/bug-gnu-emacs/2025-06/msg01274.html.

I am having issues with eglot not refreshing the errors. A work-around is to run
=eglot-reconnect= when I suspect this has happened, but it kills the speedy
feedback cycle. Hope the following helps. It it doesn't, it might be useful to
understand the above thread better.
#+begin_src emacs-lisp :tangle yes
(with-eval-after-load 'eglot
  (add-hook 'eglot-managed-mode-hook (lambda ()
                                       (flymake-mode -1)
                                       (flymake-mode 1))))
#+end_src

** Lean

This replaces =lsp-mode= by =eglot=, however, eglot seems to have a preference for
starting the language server in the project root, which is not always
appropriate for every project. Ecamples are my xmonad configuration (which lives
with the repository with =~/.config= as it's root dir). A lean4 example is the
=blockchain-lean= project. For now do not include this in my config.

#+begin_src emacs-lisp :tangle yes
(with-eval-after-load 'lsp-mode
  (setq lsp-disabled-clients '(lsp-lean))   ;; if defined in your setup
  (remove-hook 'lean4-mode-hook #'lsp-deferred))

(with-eval-after-load 'eglot
  ;; Lean 4: start LSP via lake so it picks up the project toolchain.
  (add-to-list 'eglot-server-programs
               '(lean4-mode . ("lake" "serve"))))

(add-hook 'lean4-mode-hook 'eglot-ensure)

#+end_src

Have =eglot= start the language server in the correct root by ensuring it is the
directory that contains one of these Lake files.
#+begin_src emacs-lisp :tangle yes
(after! projectile
  (dolist (f '("lakefile.lean" "lakefile.toml"))
    (add-to-list 'projectile-project-root-files-bottom-up f)
    (add-to-list 'projectile-project-root-files-top-down-recurring f)
    (add-to-list 'projectile-project-root-files f)))
#+end_src

** Haskell
#+begin_src emacs-lisp :tangle yes
(after! projectile
  (dolist (f '("cabal.project" "*.cabal"))
    (add-to-list 'projectile-project-root-files-bottom-up f)
    (add-to-list 'projectile-project-root-files-top-down-recurring f)
    (add-to-list 'projectile-project-root-files f)))
#+end_src
